### ISSUE TITLE
DLL load failed while importing swigfaiss

### ISSUE THREAD

**Issue by chrashwood** [bittremieux/falcon#9]
When trying to run Falcon on Windows Powershell (x64 run as admin) with Python 3.9, I get the following error:

```
falcon : Traceback (most recent call last):
At line:1 char:1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\faiss\loader.py", line 34, in <module>
    from .swigfaiss import *
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\faiss\swigfaiss.py", line 13, in 
<module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chras\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\chras\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chras\AppData\Local\Programs\Python\Python39\Scripts\falcon.exe\__main__.py", line 4, in <module>
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\falcon\falcon.py", line 22, in <module>
    from .cluster import cluster, spectrum
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\falcon\cluster\cluster.py", line 6, in 
<module>
    import faiss
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\faiss\__init__.py", line 17, in 
<module>
    from .loader import *
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "c:\users\chras\appdata\local\programs\python\python39\lib\site-packages\faiss\swigfaiss.py", line 13, in 
<module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.
```
Falcon was installed via pip.

**Comment by bittremieux** [comment]
Apologies, I forgot to include in the README that only Linux and OSX are supported. _falcon_ uses the [Faiss library](https://github.com/facebookresearch/faiss) for fast nearest neighbor searching, which unfortunately does not support Windows.

I have made a note of this in the README now.
